addons:
  apt:
    packages:
    - xsltproc
    - xmlstarlet
after_success:
- "set -e\nif [[ -n $CMD_AFTER_SUCCESS\n      && $SKIP_CI == 'false'\n   ]];\nthen\n    eval $CMD_AFTER_SUCCESS;\n    echo \"CMD_AFTER_SUCCESS is finished\";\nfi\n"
- "set -e\nSKIP_DEPLOY=$(if [ $(git log -1 | grep -E \"\\[maven-release-plugin\\] prepare release\" | cat | wc -l) -lt 1 ]; then echo false; else echo true; fi;)\nif [[ $TRAVIS_REPO_SLUG == 'checkstyle/checkstyle'\n        && $TRAVIS_BRANCH == 'master'\n        && $TRAVIS_PULL_REQUEST == 'false'\n        && $DEPLOY == 'true'\n        && $SKIP_CI == 'false'\n        && $SKIP_DEPLOY == 'false'\n   ]];\nthen\n    mvn -s config/deploy-settings.xml -Pno-validations deploy;\n    echo \"deploy to maven snapshot repository is finished\";\nfi\n"
before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
branches:
  only:
  - master
cache:
  apt: true
  directories:
  - ~/.m2
install:
- "if [ \"${TRAVIS_OS_NAME}\" == \"osx\" ]; then\n  # https://github.com/travis-ci/travis-ci/issues/6307#issuecomment-233315824\n  rvm get head\nfi\n"
language: java
matrix:
  fast_finish: true
  include:
  - env:
    - DESC="test Issue ref in PR description"
    - CMD="./.ci/travis/travis.sh pr-description"
  - env:
    - DESC="tests and deploy"
    - CMD="mvn clean integration-test failsafe:verify"
    - DEPLOY="true"
    jdk: oraclejdk8
  - env:
    - DESC="checkstyle and sevntu-checkstyle"
    - CMD="mvn clean verify -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true"
    jdk: oraclejdk8
  - env:
    - DESC="cobertura and codecov"
    - CMD="./.ci/travis/travis.sh cobertura-check"
    - CMD_AFTER_SUCCESS="bash <(curl -s https://codecov.io/bash)"
    jdk: oraclejdk8
  - env:
    - DESC="findbugs and pmd"
    - CMD="mvn clean compile pmd:check findbugs:check"
    jdk: oraclejdk8
  - env:
    - DESC="Releasenotes generation"
    - CMD="./.ci/travis/travis.sh releasenotes-gen"
    jdk: oraclejdk8
  - env:
    - DESC="NonDex"
    - CMD="./.ci/travis/travis.sh nondex"
    jdk: oraclejdk8
  - env:
    - DESC="tests de"
    - CMD="mvn clean integration-test failsafe:verify -DargLine='-Duser.language=de -Duser.country=DE'"
    jdk: oraclejdk8
  - env:
    - DESC="tests es"
    - CMD="mvn clean integration-test failsafe:verify -DargLine='-Duser.language=es -Duser.country=ES'"
    jdk: oraclejdk8
  - env:
    - DESC="tests fi"
    - CMD="mvn clean integration-test failsafe:verify -DargLine='-Duser.language=fi -Duser.country=FI'"
    jdk: oraclejdk8
  - env:
    - DESC="tests fr"
    - CMD="mvn clean integration-test failsafe:verify -DargLine='-Duser.language=fr -Duser.country=FR'"
    jdk: oraclejdk8
  - env:
    - DESC="tests zh"
    - CMD="mvn clean integration-test failsafe:verify -DargLine='-Duser.language=zh -Duser.country=CN'"
    jdk: oraclejdk8
  - env:
    - DESC="tests ja"
    - CMD="mvn clean integration-test failsafe:verify -DargLine='-Duser.language=ja -Duser.country=JP'"
    jdk: oraclejdk8
  - env:
    - DESC="tests pt"
    - CMD="mvn clean integration-test failsafe:verify -DargLine='-Duser.language=pt -Duser.country=PT'"
    jdk: oraclejdk8
  - env:
    - DESC="tests tr"
    - CMD="mvn clean integration-test failsafe:verify -DargLine='-Duser.language=tr -Duser.country=TR'"
    jdk: oraclejdk8
  - env:
    - DESC="assembly & run '-all' jar"
    - CMD="./.ci/travis/travis.sh assembly-run-all-jar"
    jdk: oraclejdk8
  - env:
    - DESC="NoExceptionTest - Guava with google_checks"
    - CMD="./.ci/travis/travis.sh no-exception-test-guava-with-google-checks"
    jdk: oraclejdk8
  - env:
    - DESC="release dry run"
    - CMD="./.ci/travis/travis.sh release-dry-run"
    jdk: oraclejdk8
  - env:
    - DESC="check permissions on all files"
    - CMD="./.ci/travis/travis.sh check-chmod"
  - env:
    - DESC="All sevntu checks should be used"
    - CMD="./.ci/travis/travis.sh all-sevntu-checks"
    jdk: oraclejdk8
  - env:
    - DESC="MacOS verify, site, assembly"
    - CMD="export JAVA_HOME=$(/usr/libexec/java_home) && mvn package -Dlinkcheck.skip=true && mvn package -Passembly "
    os: osx
  - env:
    - DESC="sonarqube.com"
    - CMD="./.ci/travis/travis.sh sonarqube"
    jdk: oraclejdk8
  - env:
    - DESC="no error test on simple-binary-encoding"
    - CMD="./.ci/travis/travis.sh no-error-test-sbe"
    jdk: oraclejdk8
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script:
- SKIP_FILES=".github|appveyor.yml|circle.yml|distelli-manifest.yml|fast-forward-merge.sh|LICENSE|LICENSE.apache20|README.md|release.sh|RIGHTS.antlr|shippable.yml|wercker.yml"
- SKIP_CI=$(if [[ $(git diff --name-only HEAD HEAD~1 | grep -vE "$SKIP_FILES" | cat | wc -c | sed 's/^ *//' ) > 0 ]]; then echo false; else echo true; fi;)
- echo "SKIP_CI="$SKIP_CI
- "set -e\nif [[ $SKIP_CI == 'false' ]];\nthen\n     eval $CMD;\n     echo \"eval of CMD is completed\"\nfi\n"
sudo: false
